In [3]:
import streamlit as st
import numpy as np
import pandas as pd

In [4]:
np.random.randn(20, 3)

array([[ 0.10229136, -0.54196188,  0.02598923],
       [ 0.70249963, -0.46966562,  1.37316599],
       [-0.76578642, -0.01197613,  0.09712039],
       [ 0.52190215, -1.87223068, -1.3735666 ],
       [-0.98952934, -2.62606069,  0.99554289],
       [-2.41604732,  1.03733207, -0.50993962],
       [ 0.05283241,  0.02772067, -0.13334781],
       [ 0.60340068, -0.05171859, -1.25747393],
       [-0.58078493, -0.77097496,  1.14830227],
       [ 1.23122875,  1.25301615, -1.27826744],
       [-0.8852917 , -2.43712061, -0.65300923],
       [-1.71914258, -0.20194015,  0.10784209],
       [-0.16934597,  1.30173696,  0.58297384],
       [ 0.55391758, -0.63146506,  0.6645241 ],
       [-0.60905832, -1.2608763 ,  0.67521092],
       [-1.47794014,  1.48413078, -0.12235899],
       [ 0.5305114 ,  0.46454383, -1.54194234],
       [-0.6328039 , -0.15203637, -2.19075339],
       [-0.51735542, -1.24530266,  0.44221825],
       [ 0.32612651, -2.31132151, -0.10933379]])

In [11]:
chart_data = pd.DataFrame(
     np.random.randn(20, 3),
     columns=['a', 'b', 'c'])
chart_data

a         b         c
0   1.157706  0.824187 -0.326053
1   0.074776  0.909315  0.389037
2   0.469512 -1.085996  0.020985
3   0.062221  0.256454 -1.171171
4  -0.021546 -1.082525 -2.748443
5  -0.110861 -1.433098  0.948843
6  -0.551417  1.499690 -0.968772
7   0.657169 -0.647033 -0.823641
8  -1.786187  1.261603  1.333605
9  -0.408243 -1.226114 -0.278294
10 -0.291162 -0.843100 -0.914754
11 -0.072779  0.192083  0.341443
12  0.380578  0.458038 -0.180115
13  0.253162  0.458090 -0.857014
14 -1.980324 -0.145453  0.263719
15  0.224639  1.563216  0.501697
16  0.502827  0.585660  0.792931
17  0.955434  0.640095  0.248142
18  1.764272  0.472410 -0.677751
19 -0.157289 -2.841476  0.443778

In [12]:
np.random.randn(1000, 2) / [50, 50] + [37.76, -122.4],

(array([[  37.79083492, -122.42194444],
        [  37.76172585, -122.42571025],
        [  37.78140772, -122.41973083],
        ...,
        [  37.74325443, -122.37879724],
        [  37.75195324, -122.3884409 ],
        [  37.78968749, -122.38985778]]),)

In [33]:
a = np.random.randn(1, 2)
a

array([[-0.57553946,  0.35169756]])

In [34]:
a/[50, 50] + [37.76, -122.4]

array([[  37.74848921, -122.39296605]])